version: 1
validation: sovereign
default_denom: ignt
accounts: 
- name: alice
  coins:
  - 20000token
  - 200000000ignt
- name: bob
  coins:
  - 10000token
  - 100000000ignt
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
validators:
- name: alice
  bonded: 100000000ignt
- name: validator1
  bonded: 200000000ignt
- name: validator2
  bonded: 100000000ignt